<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class DatabaseH1 extends Model
{
    protected $primaryKey = 'id_database_h1';
    protected $table = 'database_h1';
    protected $fillable = [      
        'id_dealer',
        'no_faktur',
        'no_rangka',
        'kode_mesin',
        'no_mesi',
        'tgl_cetak',
        'tgl_mohon',
        'nama',
        'alamat',
        'kel',
        'kec',
        'kode_kota',
        'kota_pos',
        'kode_prov',
        'cash_credit',
        'ktp_no',
        'finance_company',
        'down_payment',
        'tenor',
        'email',
        'kode_msn',
        'no_mesin2',
        'no_ktp',
        'jenis_sales',
        'gender',
        'tgl_lahir',
        'alamat3',
        'kel4',
        'kec5',
        'kota_kab',
        'kode_pos6',
        'propinsi',
        'agama',
        'pekerjaan',
        'pengeluaran',
        'pendidikan',
        'PIC',
        'no_hp',
        'no_telp',
        'dihubungi',
        'merk',
        'jenis',
        'fungsi',
        'pemakai',
        'sales_person',
        'umur',
        'range_umur',
        'region',
        'tipe',
        '6_jenis',
        '3_jenis',
        'verify_flag',
        'verify_date',
        'buyer_name',
        'buyer_address',
        'buyer_kelurahan',
        'buyer_kecamatan',
        'flag_update_no_h_p',
        'flag_update_tgl_lahir',
        'flag_update_agama',
        'flag_update_pekerjaan',
        'flag_update_cash_credit',
        'flag_update_fin',
        'email2',
        'status_rumah',
        'status_handphone',
        'status_verifikasi',
        'DP_aktual',
        'tenor2',
        'cicilan',
        'tipe_ATPM',
        'warna',
        'tipe_var_plus',
        'cust_no',
        'RO_type',
        'RO_data',
        'member_no',
        'facebook',
        'twitter',
        'instagram',
        'youtube',
        'hobi',
        'remark',
        'Referall_ID',
        'flag_DP',
        'flag_tenor',
        'flag_cicilan',
        'flag_email',
        'flag_hobi',
        'flag_keterangan',
        'W',
        'no_KK',
        'reference',
        'RO_by_desi',
        'tempat_lahir',
        'nama_instansi',
        'alamat_instansi',
        'kecamatan_instansi',
        'kota_instansi',
        'propinsi_instansi',
        'aktifitas_penjualan',
        'kode_pekerjaan2'
    ];

    protected $hidden = ['id_database_h1', 'updated_at', 'created_at'];

    public function getTableColumns() {
        return $this->getConnection()->getSchemaBuilder()->getColumnListing($this->getTable());
    }

    public function dealer(){
        return $this->belongsTo('App\Dealer', 'id_dealer', 'id_dealer');
    }
}
